### ISSUE TITLE
AttributeError: module 'partridge' has no attribute 'feed'

### ISSUE THREAD

**Issue by junrent** [worldbank/GOST_PublicGoods#2]
I set up a new env and installed:
•	conda install –c conda-forge geopandas 
•	pip install osmnx
•	pip install peartree
•	conda install rasterio
•	pip install ipykernel

Now, importing the packages (in flooding example.ipynb) throws  
_AttributeError: module 'partridge' has no attribute 'feed'_

I get the same error with rasterio versions 0.36.0, 1.0.7, and 1.0.13

**Comment by bpstewar** [comment]
Could you expand on the error - copy thoe whole error message? That error message come from the peartree library, what version of that do you have?

**Comment by junrent** [comment]
I use peartree 0.6.0. 
Here is the full message:
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-d1d45ba1e8e1> in <module>
      4 gostNetsFolder = os.path.dirname(os.getcwd())
      5 sys.path.insert(0, gostNetsFolder)
----> 6 from GOSTNets import GOSTnet as gn
      7 importlib.reload(gn)
      8 

~\OneDrive - WBG\City scans\Network analysis\Kampala\GOSTNets\GOSTNets\GOSTnet.py in <module>
----> 1 import peartree as pt
      2 import peartree.graph as ptg
      3 print('peartree version: %s ' % pt.__version__)
      4 import networkx as nx
      5 print('networkx version: %s ' % nx.__version__)

C:\WBG\anaconda3\envs\GOSTnet\lib\site-packages\peartree\__init__.py in <module>
      3 
      4 from peartree.__version__ import __version__  # noqa: F401
----> 5 from peartree.paths import (
      6         load_feed_as_graph,
      7         get_representative_feed,

C:\WBG\anaconda3\envs\GOSTnet\lib\site-packages\peartree\paths.py in <module>
      5 import partridge as ptg
      6 
----> 7 from .graph import (generate_empty_md_graph, generate_summary_graph_elements,
      8                     make_synthetic_system_network, populate_graph)
      9 from .synthetic import SyntheticTransitNetwork

C:\WBG\anaconda3\envs\GOSTnet\lib\site-packages\peartree\graph.py in <module>
      7 
      8 from .settings import WGS84
----> 9 from .summarizer import (generate_edge_and_wait_values,
     10                          generate_summary_edge_costs,
     11                          generate_summary_wait_times)

C:\WBG\anaconda3\envs\GOSTnet\lib\site-packages\peartree\summarizer.py in <module>
    419 
    420 def generate_edge_and_wait_values(
--> 421         feed: ptg.feed,
    422         target_time_start: int,
    423         target_time_end: int,

AttributeError: module 'partridge' has no attribute 'feed'
`

**Comment by bpstewar** [comment]
I think the problem is with the partridge library, not the peartree library; I am encoutering the same problem on another environment, but not my original, still working environment. My solution is to install a specific version of partridge that works

```
> pip uninstall partridge
> pip install partridge==0.11.0

```
I have created an issue on the peartree repo, hopefully it is solved sometime soon - https://github.com/kuanb/peartree/issues/119

**Comment by junrent** [comment]
Great, that worked. 
For the record, I can run Flooding_example.ipynb with following package versions:
peartree version: 0.6.0 
networkx version: 2.2 
matplotlib version: 3.0.2 
osmnx version: 0.8.2 
partridge version: 0.11.0
rasterio version: 0.36.0
