### ISSUE TITLE
gn.sample_raster() fails in rasterio 1.0.9

### ISSUE THREAD

**Issue by junrent** [worldbank/GOST_PublicGoods#3]
In Flooding_example.ipynb following line throws an error when running with rasterio 1.0.9. (no problem with rasterio 0.36.0): 
`G = gn.sample_raster(G, tif_path, property_name = 'flood_depth')`

And here is the error message:

> ---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-16-97fd4c4ce7f6> in <module>
----> 1 G = gn.sample_raster(G, tif_path, property_name = 'flood_depth')

~\OneDrive - WBG\City scans\Network analysis\Kampala\GOSTNets\GOSTNets\GOSTnet.py in sample_raster(G, tif_path, property_name)
    316 
    317     # create list of values
--> 318     raster_values = list(dataset.sample(list_of_nodes.values()))
    319     raster_values = [x[0] for x in raster_values]
    320 

C:\WBG\anaconda3\envs\GOSTnet2\lib\site-packages\rasterio\sample.py in sample_gen(dataset, xy, indexes)
     21             window = Window(col_off, row_off, 1, 1)
     22             data = read(indexes, window=window, masked=False)
---> 23             yield data[:, 0, 0]

IndexError: index 0 is out of bounds for axis 1 with size 0

Any suggestions? Thanks!

**Comment by Charlesfox1** [comment]
Hey Jun,

Ben is going to adjust this function. It’s down to the fact that some points lie outside the boundary of the raster. It’s bad coding on rasterio’s side, but it’s a ‘plausible error’.

Sample taster in future releases of GOSTnets will check that all points are inside the raster area before attempting to sample.

Hope this makes sense.

C

**Comment by bpstewar** [comment]
I have updated the code to work with sample_raster. While the function now works, the network nodes outside the raster end up without the flood_depth attribute at all. As long as that is correct, I believe this is completed
